### ISSUE TITLE
Unable to access pData/fData

### ISSUE THREAD

**Issue by ccruizm** [cole-trapnell-lab/garnett#20]
Hi there,

I have an issue after classifying my cells using `classify_cells`. When I want to access the pData, I have found the next error:

```
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'fData' for signature '"CellDataSet"'
Traceback:

1. head(fData(gbm_cds))
2. fData(gbm_cds)
3. (function (classes, fdef, mtable) 
 . {
 .     methods <- .findInheritedMethods(classes, fdef, mtable)
 .     if (length(methods) == 1L) 
 .         return(methods[[1L]])
 .     else if (length(methods) == 0L) {
 .         cnames <- paste0("\"", vapply(classes, as.character, 
 .             ""), "\"", collapse = ", ")
 .         stop(gettextf("unable to find an inherited method for function %s for signature %s", 
 .             sQuote(fdef@generic), sQuote(cnames)), domain = NA)
 .     }
 .     else stop("Internal error in finding inherited methods; didn't return a unique method", 
 .         domain = NA)
 . })(list(structure("CellDataSet", package = "monocle")), new("standardGeneric", 
 .     .Data = function (x) 
 .     standardGeneric("fData"), generic = structure("fData", package = "monocle3"), 
 .     package = "monocle3", group = list(), valueClass = character(0), 
 .     signature = "x", default = NULL, skeleton = (function (x) 
 .     stop("invalid call in method dispatch to 'fData' (no default method)", 
 .         domain = NA))(x)), <environment>)
4. stop(gettextf("unable to find an inherited method for function %s for signature %s", 
 .     sQuote(fdef@generic), sQuote(cnames)), domain = NA)
```

This is the structure of my data:

```
CellDataSet (storageMode: environment)
assayData: 32738 features, 4002 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: AAACCCACAGTCGCTG-1 AAACCCACAGTGTATC-1 ...
    TTTGTTGAGGTCGTGA-1 (4002 total)
  varLabels: Size_Factor garnett_cluster cell_type cluster_ext_type
  varMetadata: labelDescription
featureData: none
experimentData: use 'experimentData(object)'
Annotation:  
```

I do not understand where the issue is. When I check the object obtained after training the classifier, the data class is the same (`CellDataSet (storageMode: environment)`) and I am able to access with `pData` the `varLabels: size factors` stored in that object.

P.S. I have tried to access the small dataset included in the package but wasn't able to load the `mat` object. I checked the GitHub repository and the `exprs.txt` doesn't exist. 

Thanks for your help!
